### ISSUE TITLE
Error: Expected boundary; Line 11

### ISSUE THREAD

**Issue by chdagenais** [msindwan/mhtml2html#28]
Trying to use from command line to convert mhtml to html

Always getting this error, with any mhtml files I have to convert.

```
Error: Expected boundary; Line 11
    at i (/usr/local/lib/node_modules/mhtml2html/dist/mhtml2html.js:1:1684)
    at Object.parse (/usr/local/lib/node_modules/mhtml2html/dist/mhtml2html.js:1:3565)
    at Object.convert (/usr/local/lib/node_modules/mhtml2html/dist/mhtml2html.js:1:4442)
    at /usr/local/lib/node_modules/mhtml2html/index.js:34:36
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
```

V 3.0.0

enabling or disabling the convertIframe option gives the same error

**Comment by msindwan** [comment]
Hi @charlesdagenais can you please provide an example mhtml file you are using? Were these files generated by chrome?

**Comment by fira42073** [comment]
I have the same problem, while trying to convert this file

[Оскорбление чувств играющих — Ртуть.zip](https://github.com/msindwan/mhtml2html/files/8334847/default.zip)

**Comment by rg-software** [comment]
Same for me, using [these examples](https://www.fileformat.info/format/mime-html/sample/index.htm).

**Upd**: I made a quick fix it in [my own fork](https://github.com/rg-contributions/mhtml2html).
