### ISSUE TITLE
Mhtml Error

### ISSUE THREAD

**Issue by yooper** [msindwan/mhtml2html#6]
I received this error while trying to convert your github page,  https://github.com/msindwan/mhtml2html . Any suggestions on how to resolve this error?

```
Uncaught Error: MHTML error: invalid frames
    at assert (mhtml2html.js:3714)
    at Object.convert (mhtml2html.js:3990)
```

**Comment by msindwan** [comment]
@yooper very sorry for the delay, I'm not sure why I didn't receive a notification for this issue. 

This issue is a result of an invalid mhtml file. I was able to successfully save this page and convert it. What browser are you using to generate the mhml file?

**Comment by sarimabbas** [comment]
I have a similar issue, I am using Electron's `webcontents.savePage` feature (https://www.electronjs.org/docs/api/web-contents#contentssavepagefullpath-savetype), which should be the same as Chrome/Chromium. I can supply a saved MHTML file, if that helps?

**Comment by msindwan** [comment]
Hi @sarimabbas yes that would be very helpful. Can you also specify which version you have installed?

**Comment by sarimabbas** [comment]
Sure, my MHTML version is `^3.0.0` and Electron is `^8.0.3`. 

Attached is the MHTML file as an archive. It opens fine in Chrome, but throws an error when run through `mhtml2html`. 

[page.mhtml.zip](https://github.com/msindwan/mhtml2html/files/4326216/page.mhtml.zip)

**Comment by msindwan** [comment]
@sarimabbas how are you invoking mhtml2html? `yarn mhtml2html page.mhtml out.html` doesn't produce any errors for me

**Comment by sarimabbas** [comment]
Thanks so much! I tried to use the Node.js programmatic API using the following code:

```js
        await win.webContents.savePage(pathToPage, "MHTML");
        const mhtmlFileContents = fs.readFileSync(pathToPage);
        const htmlDoc = mhtml2html.convert(mhtmlFileContents, {
          parseDOM: html => new JSDOM(html)
        });
        console.log(htmlDoc);
```

and got this error:

```
asyncToGenerator.js?1da1:6 Uncaught (in promise) Error: Could not call remote method 'convert'. Check that the method signature is correct. Underlying error: MHTML error: invalid frames
Underlying stack: Error: MHTML error: invalid frames
    at i (/Users/sarimabbas/Developer/.../src/frontend/node_modules/mhtml2html/dist/mhtml2html.js:1:1684)
    at Object.convert (/Users/sarimabbas/Developer/.../src/frontend/node_modules/mhtml2html/dist/mhtml2html.js:1:4549)
    at electron/js2c/browser_init.js:6702:67
    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:6567:27)
    at IpcMainImpl.emit (events.js:210:5)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3861:23)
    at WebContents.emit (events.js:210:5)

    at electron/js2c/browser_init.js:6705:21
    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:6567:27)
    at IpcMainImpl.emit (events.js:210:5)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3861:23)
    at WebContents.emit (events.js:210:5)
```

Strangely, when I read the MHTML file using `fs.readFileSync(path, "utf8")`, I get a different error:

```
asyncToGenerator.js?1da1:6 Uncaught (in promise) Error: Could not call remote method 'convert'. Check that the method signature is correct. Underlying error: Cannot read property 'window' of undefined
Underlying stack: TypeError: Cannot read property 'window' of undefined
    at Object.convert (/Users/sarimabbas/Developer/.../src/frontend/node_modules/mhtml2html/dist/mhtml2html.js:1:4790)
```

I also tried to use the Browser example code: 

```
const mhtmlFileContents = fs.readFileSync(pathToPage);
const html = mhtml2html.convert(mhtmlFileContents);
console.log(html);
```

It failed again with the `frames` error:

```
mhtml2html.js?94f4:1 Uncaught (in promise) Error: MHTML error: invalid frames
    at i (mhtml2html.js?94f4:1)
    at Object.convert (mhtml2html.js?94f4:1)
    at _callee$ (Add.vue?5f53:78)
    at tryCatch (runtime.js?96cf:45)
    at Generator.invoke [as _invoke] (runtime.js?96cf:271)
    at Generator.prototype.<computed> [as next] (runtime.js?96cf:97)
    at asyncGeneratorStep (asyncToGenerator.js?1da1:3)
    at _next (asyncToGenerator.js?1da1:25)
```

However, when I used `fs.readFileSync(path, "utf8")` this time, it worked **successfully**! I'm not entirely sure why this inconsistent behavior might be occurring, it's entirely possible it's due to the way it was saved by Electron. 

Thank you for your help!

**Comment by msindwan** [comment]
Glad you got it working! Reading the file with utf8 encoding makes sense but I'm not sure why the window error would occur. It's possible that it failed to parse the HTML. Please keep me posted if you continue to see the error!
